### ISSUE TITLE
Problems when evaluating and predicting

### ISSUE THREAD

**Issue by ccbbvv** [alikm6/DEU-Net#1]
![Snipaste_2024-01-10_16-29-24](https://github.com/alikm6/DEU-Net/assets/116136253/a6a420ca-ca5b-42f4-a43e-800a7bfb4678)
![Snipaste_2024-01-10_16-29-38](https://github.com/alikm6/DEU-Net/assets/116136253/e7cb5cde-b423-476d-bc47-9518ca6efce6)

Hello, this problem keeps appearing when making predictions. Why is this?

**Comment by alikm6** [comment]
Hello,

It seems that the network configuration file address has been entered incorrectly. What command did you use for prediction?

For prediction, you should run the `predict.py` script as follows:
```
python predict.py --cfg "cfg/net/dual-encoder-unet.cfg" --model "checkpoints/checkpoint_best.pth" -i "datasets/ISIC2017/ISIC-2017_Test_v2_Data/ISIC_0012265.jpg"
```

In the above command, replace `cfg/net/dual-encoder-unet.cfg` with the path where the network configuration file is located, `checkpoints/checkpoint_best.pth` with the path where the trained network weights are located, and `datasets/ISIC2017/ISIC-2017_Test_v2_Data/ISIC_0012265.jpg` with the path to the image you want to perform prediction on.

**Comment by ccbbvv** [comment]
> Hello,
> 
> It seems that the network configuration file address has been entered incorrectly. What command did you use for prediction?
> 
> For prediction, you should run the `predict.py` script as follows:
> 
> ```
> python predict.py --cfg "cfg/net/dual-encoder-unet.cfg" --model "checkpoints/checkpoint_best.pth" -i "datasets/ISIC2017/ISIC-2017_Test_v2_Data/ISIC_0012265.jpg"
> ```
> 
> In the above command, replace `cfg/net/dual-encoder-unet.cfg` with the path where the network configuration file is located, `checkpoints/checkpoint_best.pth` with the path where the trained network weights are located, and `datasets/ISIC2017/ISIC-2017_Test_v2_Data/ISIC_0012265.jpg` with the path to the image you want to perform prediction on.

Thank you very much, the problem has been solved！！！

**Comment by wmxxxxxxxxx** [comment]
Hello,this problem keeps appearing when making evaluations.why is this?
![5$@@2}$M9OP)7V5{SN5{` P](https://github.com/alikm6/DEU-Net/assets/93987304/14fdb844-4a48-45fd-9f29-d7ca92ed1670)

**Comment by alikm6** [comment]
> Hello,this problem keeps appearing when making evaluations.why is this? ![5$@@2}$M9OP)7V5{SN5{` P](https://private-user-images.githubusercontent.com/93987304/333519150-14fdb844-4a48-45fd-9f29-d7ca92ed1670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDkzMDQsIm5iZiI6MTcxNzI0OTAwNCwicGF0aCI6Ii85Mzk4NzMwNC8zMzM1MTkxNTAtMTRmZGI4NDQtNGE0OC00NWZkLTlmMjktZDdjYTkyZWQxNjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDEzMzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViY2I3NWY1ZjAxZmFmYjNmNTFhNTU2Njg1MmVhNzVlM2ZmNDdhNWFkMzVjZjZjNTg0NTQwNDIyYTdjYzc0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RyzS6NTsW_YjYbxuODK6Z4xd0-7z3_Phk166mP4-jG4)

The error happens because the number of config files (`--cfg`) and the number of model files (`--model`) you provided are not the same. Make sure you have the same number of each when you run the evaluation script.

**Comment by wmxxxxxxxxx** [comment]
I have solved this problem, tnank you.I would like to ask, if I want to use this network to divide a three-category problem, then what parts should I change? I changed num_output_channels in the cfg file to 3, and num_classes in the model file to int=3, but it kept reporting a dimension mismatch.

**Comment by alikm6** [comment]
> I have solved this problem, tnank you.I would like to ask, if I want to use this network to divide a three-category problem, then what parts should I change? I changed num_output_channels in the cfg file to 3, and num_classes in the model file to int=3, but it kept reporting a dimension mismatch.

For a three-class task, you'll need to make some changes beyond just updating `num_output_channels`.

Specifically, you'll need to modify the mask preprocessing section in the `preprocess` function of the `SkinLesionDataset` class. The current code is designed for one- and two-class tasks, so it won't handle more than two classes correctly without this adjustment. Other parts of the code might work as they are, but I haven't fully debugged it for tasks with more than two classes, so there could be some bugs.

**Comment by wmxxxxxxxxx** [comment]
Thank you, could you please specify which part of SkinLesionDataset class I should modify?
